name: Publish to Dockerhub

on:
  release:
    types: [ published ]
  push:
    branches:
      - development

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          tools: composer
          coverage: none

      - name: Install Dependencies
        run: composer install --no-interaction --no-progress --ansi

      - name: Run PHPStan
        run: composer analyse

      - name: Run Laravel Pint
        run: composer sniff

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: domenikus/channel-creator-bot

      - name: Get Version
        id: get_version
        uses: battila7/get-version-action@v2

      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          build-args:
            version=${{steps.get_version.outputs.version}}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
