name: Code Style & Static analysis

on: pull_request

jobs:
  analyse:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          tools: composer
          coverage: none

      - name: Install Dependencies
        run: composer install --no-interaction --no-progress --ansi

      - name: Run PHPStan
        run: composer analyse

      - name: Run Laravel Pint
        run: composer sniff
